### ISSUE TITLE
Error on product page

### ISSUE THREAD

**Issue by simthax** [magefan/hyva-theme-auto-related-product-plus#1]
Hello,

Got the following error on the product page when this module is enabled
`Error: Cannot instantiate abstract class Magento\Framework\View\Element\AbstractBlock in /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121`

Module versions: 
hyva-themes/magento2-default-theme: 1.3.1
magefan/module-auto-related-product-plus: 2.2.0
magefan/hyva-theme-auto-related-product-plus: 2.0.1
hyva-themes/magento2-compat-module-fallback: 1.1.2

Thanks

**Comment by magefan** [comment]
Hello @simthax , thank you for your report. Could you please contact us regarding this issue using the contact form on our website https://magefan.com/contact and provide the order number for the Auto Related Plus Extension?
